module.exports.data = [
	{
	"_id": {
		"$oid": "5db66de525dcb21797033c8b"
	},
	"SourceUrl": "https://austin.craigslist.org/sks/d/austin-best-value-wood-tile-laminate/6961597184.html",
	"PostDate": "2019-08-21T13:13:34-0500",
	"PostDateValue": "2019-08-21T13:13:34-05:00",
	"Category": "Household & Labor",
	"SubCategory": "Lawn service",
	"CategoryResolved": true,
	"CategoryResolveScore": 0.2,
	"AddressResolved": false,
	"AddressResolveScore": 0.0,
	"Address": null,
	"Address2": null,
	"City": "austin",
	"State": "TX",
	"Zip": null,
	"Longitude": "-97.639600",
	"LongitudeValue": -97.6396,
	"Lattitude": "30.296000",
	"LattitudeValue": 30.296,
	"PosterName": null,
	"Phone": null,
	"Email": null,
	"Title": "Best Value Wood Tile Laminate &amp; Vinyl Flooring Installations",
	"Description": "\n        \nIf you're thinking about installing new floors, you've clicked on the right ad. When you choose me, you get the highest quality of work available at the the lowest price, so low that other contractors frequently subcontract out to me the flooring and tile portions of their general remodels. I have 7 years of experience with hundreds of floors and references under my belt, and take great pride in my work.\n\nI'm fast, reliable, attentive to detail, and I'll work the project straight through to completion with no interruptions. I also require no upfront payment. Everyone has always been very happy with my workmanship.\n\nMy pricing is simple and straightforward with no surprises or nickle &amp; diming. Due to my speed, efficiency, low overhead, and lack of advertising budget, and the fact that I don't spin my wheels doing drive out estimates, I'm able to provide service for a much lower cost than my competitors. I'm a perfectionist and warranty all my work from 3-5 years depending on material. I'm used to working with investors, flippers, real estate agents, and other professionals.\n\nI believe in full transparency unlike box stores like Home Depot or Lowes, who advertise a lower price/sq ft than I do, but charge more than double my final rates on average, once you factor in the underlayment, and the trim, and the quarter round, and all the miscellaneous charges they have. As a quick example, my toilet removal/replacement fee is $100 vs the $300 I saw on the last box store quote.\n\nSo that you can plan your own project cost, I have included a cost breakdown summarized below:\n\nInstallation:\nLaminate &amp; Vinyl $1.25/ft\nEngineered Wood - Floating $1.50/ft, Nail-Down $2.00/ft, Glue-Down $2.25/ft\nTile - $2-3/ft depending on type\nShowers/Backsplashes/Mosaics - on a case by case basis\nStairs - $40-60/step\n\nRemoval:\nCarpet: $.25/ft\nLaminate/Vinyl/Floating Wood: $.50/ft\nTile: $1.50/ft\nGlue-Down Wood: $2.00/ft\n\nMiscellaneous:\nToilet Removal/Replacement - $50/$50\nBaseboard Removal &amp; Replacement Instead of Quarter Round Install $.50/ft\nQuarter Round Removal: $1.00/ft\nFloor Leveling $35/bag\nAppliance Removal Shuffle &amp; Replacement $25 each.\nFurniture Shuffle case by case starting at $10/item\nUndercutting of Stone Fireplaces $50 (standard size)\nUndercutting Door Frames - $10 - only applicable on small jobs or those with high door/area ratios.\nDeliver: $100/1000lbs\nTrash Haul $200/truck load\n\nThese above are turn-key, including all miscellaneous and necessary steps from grouting to moisture barrier to trim and quarter round. Prices assume open areas, free of furniture. If that isn't the case, then call to discuss the scope of the furniture shuffle required. Here are before and after photos from jobs I've done over the years.    ",
	"ImageUrls": [
		"https://images.craigslist.org/00i0i_iUtWcuHqxUO_50x50c.jpg",
		"https://images.craigslist.org/00O0O_aGe8eUPMskS_50x50c.jpg",
		"https://images.craigslist.org/00f0f_k0Vo4615NIe_50x50c.jpg",
		"https://images.craigslist.org/00e0e_84aip1nmgXN_50x50c.jpg",
		"https://images.craigslist.org/00z0z_7ScA7LRXyg9_50x50c.jpg",
		"https://images.craigslist.org/01010_2dj26CQLgF8_50x50c.jpg",
		"https://images.craigslist.org/00X0X_df07IbzA5NP_50x50c.jpg",
		"https://images.craigslist.org/00K0K_a90nxKX5L5J_50x50c.jpg",
		"https://images.craigslist.org/00d0d_fItFNSCggGM_50x50c.jpg",
		"https://images.craigslist.org/00D0D_cgJTZD9jomr_50x50c.jpg",
		"https://images.craigslist.org/01111_5Q7bBH3pyy6_50x50c.jpg",
		"https://images.craigslist.org/00N0N_hqYEodjOOvf_50x50c.jpg",
		"https://images.craigslist.org/01414_hYf5n9bMgL7_50x50c.jpg",
		"https://images.craigslist.org/00y0y_kFsaoZyUMRh_50x50c.jpg",
		"https://images.craigslist.org/01212_3MtoMVovrGX_50x50c.jpg",
		"https://images.craigslist.org/00X0X_8UKl9ZNXxFc_50x50c.jpg",
		"https://images.craigslist.org/00H0H_iCH2v2ZZeZ1_50x50c.jpg",
		"https://images.craigslist.org/00505_4ljhB8QOIgP_50x50c.jpg",
		"https://images.craigslist.org/00m0m_aQpF9eWazl5_50x50c.jpg",
		"https://images.craigslist.org/00R0R_7zmmaU49zC7_50x50c.jpg",
		"https://images.craigslist.org/00F0F_5brZ6Zzkk5S_50x50c.jpg",
		"https://images.craigslist.org/01212_52JqorkvRDd_50x50c.jpg",
		"https://images.craigslist.org/00E0E_4CE15NrmO6l_50x50c.jpg",
		"https://images.craigslist.org/01717_h4fpPlCYOQP_50x50c.jpg"
	],
	"WebSite": "1.25/ft"
},
{
	"_id": {
		"$oid": "5db66de525dcb21797033c8c"
	},
	"SourceUrl": "https://austin.craigslist.org/aos/d/austin-mister-rover-mobile-mechanic/6961588474.html",
	"PostDate": "2019-08-21T13:04:17-0500",
	"PostDateValue": "2019-08-21T13:04:17-05:00",
	"Category": "Lessons",
	"SubCategory": "Music",
	"CategoryResolved": true,
	"CategoryResolveScore": 0.20666666666666664,
	"AddressResolved": false,
	"AddressResolveScore": 0.0,
	"Address": null,
	"Address2": null,
	"City": "austin",
	"State": "TX",
	"Zip": null,
	"Longitude": "-97.720396",
	"LongitudeValue": -97.720396,
	"Lattitude": "30.232393",
	"LattitudeValue": 30.232393,
	"PosterName": null,
	"Phone": "5124818877",
	"Email": null,
	"Title": "Mister Rover mobile Mechanic",
	"Description": "\n        \nWe come to you . General maintenance oil changes, brake jobs, alternator, wheel bearing , radiators and more please feel free to call 5124818877 Free Estimate.    ",
	"ImageUrls": [],
	"WebSite": null
},
{
	"_id": {
		"$oid": "5db66de525dcb21797033c8d"
	},
	"SourceUrl": "https://austin.craigslist.org/lss/d/austin-serious-inquires-20-per-session/6961577748.html",
	"PostDate": "2019-08-21T12:52:54-0500",
	"PostDateValue": "2019-08-21T12:52:54-05:00",
	"Category": "Lessons",
	"SubCategory": "Tutors ",
	"CategoryResolved": true,
	"CategoryResolveScore": 0.19523809523809527,
	"AddressResolved": false,
	"AddressResolveScore": 0.0,
	"Address": null,
	"Address2": null,
	"City": "austin",
	"State": "TX",
	"Zip": null,
	"Longitude": "-97.716600",
	"LongitudeValue": -97.7166,
	"Lattitude": "30.263800",
	"LattitudeValue": 30.2638,
	"PosterName": null,
	"Phone": "8045190645",
	"Email": null,
	"Title": "SERIOUS INQUIRES! $20 PER SESSION!! Train to Live !!",
	"Description": "\n        \nSERIOUS INQUIRES ONLY!!! \nDon’t commit unless your ready . \n\nAre you feeling unmotivated?\nLacking energy? \nNot satisfied with your appearance?\nI'm here to help !!! \nI'm ready to work with you!\nAll I ask in return is your dedication, ambition, and consistency! \nBring your A+ game !💪🏾\n\n\n1 on 1 sessions ✔\nGym workouts✔\nHouse calls ✔ \nGroup sessions ✔\n\nSessions can also be created for your spare time when your not working with me !👍🏿\n\n\n\n$20 per session !! Pending on the distance (1 hour) Give me a call or text. \n \nCorey 8045190645 or contact me through email.    ",
	"ImageUrls": [
		"https://images.craigslist.org/01010_dCboVt9W12K_50x50c.jpg",
		"https://images.craigslist.org/00s0s_50owhUzbrXX_50x50c.jpg",
		"https://images.craigslist.org/00q0q_jNphghjZmq9_50x50c.jpg",
		"https://images.craigslist.org/00q0q_kJuuk8E17OK_50x50c.jpg",
		"https://images.craigslist.org/00q0q_cwXTFhx3q6s_50x50c.jpg",
		"https://images.craigslist.org/00x0x_erTDleY69IO_50x50c.jpg",
		"https://images.craigslist.org/00Q0Q_2Bs5OKOHnbC_50x50c.jpg",
		"https://images.craigslist.org/00101_b4WMUvjacW7_50x50c.jpg",
		"https://images.craigslist.org/00b0b_dlcDKBoEacn_50x50c.jpg",
		"https://images.craigslist.org/00b0b_jzDkaGpPenA_50x50c.jpg",
		"https://images.craigslist.org/00a0a_lxtbn95m8La_50x50c.jpg",
		"https://images.craigslist.org/00m0m_5Z6sDWA9YR9_50x50c.jpg",
		"https://images.craigslist.org/00202_ZPrY2UoQTA_50x50c.jpg",
		"https://images.craigslist.org/00d0d_3J3HuvmpbNN_50x50c.jpg",
		"https://images.craigslist.org/00R0R_jfPZqTCigYc_50x50c.jpg",
		"https://images.craigslist.org/00101_k6rzZ07miBJ_50x50c.jpg",
		"https://images.craigslist.org/01010_8fG1vQp5gEW_50x50c.jpg",
		"https://images.craigslist.org/00g0g_4kXlxjAIKyR_50x50c.jpg",
		"https://images.craigslist.org/00T0T_bUJ7YFSocDj_50x50c.jpg",
		"https://images.craigslist.org/00c0c_d5LOSfnjaLn_50x50c.jpg",
		"https://images.craigslist.org/00i0i_3eZMPdvCR6K_50x50c.jpg",
		"https://images.craigslist.org/00z0z_6KEFDKbCwEj_50x50c.jpg",
		"https://images.craigslist.org/00y0y_aPvNinQL7Yp_50x50c.jpg",
		"https://images.craigslist.org/00h0h_4g4t7emqVT4_50x50c.jpg"
	],
	"WebSite": null
},
{
	"_id": {
		"$oid": "5db66de525dcb21797033c8e"
	},
	"SourceUrl": "https://austin.craigslist.org/lbs/d/austin-fast-professionally-trained/6961576411.html",
	"PostDate": "2019-08-21T12:51:33-0500",
	"PostDateValue": "2019-08-21T12:51:33-05:00",
	"Category": "Lessons",
	"SubCategory": "Driving",
	"CategoryResolved": true,
	"CategoryResolveScore": 0.21428571428571433,
	"AddressResolved": false,
	"AddressResolveScore": 0.0,
	"Address": null,
	"Address2": null,
	"City": "austin",
	"State": "TX",
	"Zip": null,
	"Longitude": "-97.735400",
	"LongitudeValue": -97.7354,
	"Lattitude": "30.285200",
	"LattitudeValue": 30.2852,
	"PosterName": null,
	"Phone": "737-932-1346",
	"Email": null,
	"Title": "🔵 FAST PROFESSIONALLY TRAINED MOVERS W/ EXCEPTIONAL SERVICE 🔵 $35/HR",
	"Description": "\n        \nOUR MOVING RECORD IS IMPECCABLE WITH THE GREATEST CREWS\n\nWE PRIDE OURSELVES IN MAKING SURE OUR CREWS ARE TRAINED\nWITH THE KNOWLEDGE, STRENGTH, DETERMINATION AND GOOD WILL\nTO DO THE BEST MOVE THEY CAN\n\nWE MAKE SURE WE HAVE ALL THE MOVING EQUIPMENT AND TOOLS NECESSARY FOR A SUCCESSFUL MOVE.\n\nWE ARE ALSO PROUD TO SAY WE HAVE A MYRIAD OF REPEAT CUSTOMERS\nAND THOSE CUSTOMERS HAVE MADE OUR REFERRAL LIST LENGTHY\n\nGIVE US A CHANCE AND YOU WON'T REGRET IT\n\nCALL US WE ARE THE MOVE MASTERS YOU ARE LOOKING FOR \n\nHUGO 737-932-1346    ",
	"ImageUrls": [],
	"WebSite": null
},
{
	"_id": {
		"$oid": "5db66de525dcb21797033c8f"
	},
	"SourceUrl": "https://austin.craigslist.org/bts/d/austin-serious-inquires-20-per-session/6961576392.html",
	"PostDate": "2019-08-21T12:51:31-0500",
	"PostDateValue": "2019-08-21T12:51:31-05:00",
	"Category": "Household & Labor",
	"SubCategory": "Lawn service",
	"CategoryResolved": true,
	"CategoryResolveScore": 0.22222222222222224,
	"AddressResolved": false,
	"AddressResolveScore": 0.0,
	"Address": null,
	"Address2": null,
	"City": "austin",
	"State": "TX",
	"Zip": null,
	"Longitude": "-97.716600",
	"LongitudeValue": -97.7166,
	"Lattitude": "30.263800",
	"LattitudeValue": 30.2638,
	"PosterName": null,
	"Phone": "8045190645",
	"Email": null,
	"Title": "SERIOUS INQUIRES! $20 PER SESSION!! Train to Live !!",
	"Description": "\n        \nSERIOUS INQUIRES ONLY!!! \nDon’t commit unless your ready . \n\nAre you feeling unmotivated?\nLacking energy? \nNot satisfied with your appearance?\nI'm here to help !!! \nI'm ready to work with you!\nAll I ask in return is your dedication, ambition, and consistency! \nBring your A+ game !💪🏾\n\n\n1 on 1 sessions ✔\nGym workouts✔\nHouse calls ✔ \nGroup sessions ✔\n\nSessions can also be created for your spare time when your not working with me !👍🏿 Instagram @2bfit_life\n\n\n\n$20 per session !! Pending on the distance (1 hour) \nGive me a call or text. \n8045190645 or contact me through email.    ",
	"ImageUrls": [
		"https://images.craigslist.org/00q0q_jNphghjZmq9_50x50c.jpg",
		"https://images.craigslist.org/00s0s_50owhUzbrXX_50x50c.jpg",
		"https://images.craigslist.org/00q0q_kJuuk8E17OK_50x50c.jpg",
		"https://images.craigslist.org/01010_dCboVt9W12K_50x50c.jpg",
		"https://images.craigslist.org/00K0K_6wJAJXh6ybv_50x50c.jpg",
		"https://images.craigslist.org/00q0q_cwXTFhx3q6s_50x50c.jpg",
		"https://images.craigslist.org/00x0x_erTDleY69IO_50x50c.jpg",
		"https://images.craigslist.org/00Q0Q_2Bs5OKOHnbC_50x50c.jpg",
		"https://images.craigslist.org/00101_b4WMUvjacW7_50x50c.jpg",
		"https://images.craigslist.org/00b0b_dlcDKBoEacn_50x50c.jpg",
		"https://images.craigslist.org/00b0b_jzDkaGpPenA_50x50c.jpg",
		"https://images.craigslist.org/00m0m_5Z6sDWA9YR9_50x50c.jpg",
		"https://images.craigslist.org/00a0a_lxtbn95m8La_50x50c.jpg",
		"https://images.craigslist.org/00202_ZPrY2UoQTA_50x50c.jpg",
		"https://images.craigslist.org/00d0d_3J3HuvmpbNN_50x50c.jpg",
		"https://images.craigslist.org/00R0R_jfPZqTCigYc_50x50c.jpg",
		"https://images.craigslist.org/00101_k6rzZ07miBJ_50x50c.jpg",
		"https://images.craigslist.org/01010_8fG1vQp5gEW_50x50c.jpg",
		"https://images.craigslist.org/01515_485ghaWB1Wf_50x50c.jpg",
		"https://images.craigslist.org/00g0g_4kXlxjAIKyR_50x50c.jpg",
		"https://images.craigslist.org/00c0c_d5LOSfnjaLn_50x50c.jpg",
		"https://images.craigslist.org/00606_dpwdLDkrwm3_50x50c.jpg",
		"https://images.craigslist.org/00w0w_8FsoWXu8IWr_50x50c.jpg",
		"https://images.craigslist.org/00o0o_ahoGy2I2fQa_50x50c.jpg"
	],
	"WebSite": null
},
{
	"_id": {
		"$oid": "5db66de525dcb21797033c90"
	},
	"SourceUrl": "https://austin.craigslist.org/lbs/d/round-rock-movers-available-fri-sat-sun/6961576011.html",
	"PostDate": "2019-08-21T12:51:07-0500",
	"PostDateValue": "2019-08-21T12:51:07-05:00",
	"Category": "Lessons",
	"SubCategory": "Driving",
	"CategoryResolved": true,
	"CategoryResolveScore": 0.21428571428571433,
	"AddressResolved": false,
	"AddressResolveScore": 0.0,
	"Address": null,
	"Address2": null,
	"City": "austin",
	"State": "TX",
	"Zip": null,
	"Longitude": "-97.706200",
	"LongitudeValue": -97.7062,
	"Lattitude": "30.508400",
	"LattitudeValue": 30.5084,
	"PosterName": null,
	"Phone": "512-551-2667",
	"Email": null,
	"Title": "===========================MOVERS - available FRI. SAT. SUN.==========",
	"Description": "\n        \nwww.CapitalMoversTexas.com\n512-551-2667\n\n\n    ",
	"ImageUrls": [],
	"WebSite": "www.CapitalMoversTexas.com"
},
{
	"_id": {
		"$oid": "5db66de525dcb21797033c91"
	},
	"SourceUrl": "https://austin.craigslist.org/trv/d/austin-yourdrivingteamcom-rvs-pets/6961569737.html",
	"PostDate": "2019-08-21T12:44:27-0500",
	"PostDateValue": "2019-08-21T12:44:27-05:00",
	"Category": "Household & Labor",
	"SubCategory": "Lawn service",
	"CategoryResolved": true,
	"CategoryResolveScore": 0.16666666666666666,
	"AddressResolved": false,
	"AddressResolveScore": 0.0,
	"Address": null,
	"Address2": null,
	"City": "austin",
	"State": "TX",
	"Zip": null,
	"Longitude": "-97.771300",
	"LongitudeValue": -97.7713,
	"Lattitude": "30.326400",
	"LattitudeValue": 30.3264,
	"PosterName": null,
	"Phone": null,
	"Email": null,
	"Title": "YourDrivingTeam.com ( RV&#39;s - Pets- Vehicles - Rental Trucks - Riders )",
	"Description": "\n        \n\nYour Driving Team\n\nA Driving Team That Has Your Best Interest In Mind\n\nPersonal Long Distance Driving\n\nYour Driving Team specializes in personal long-distance transportation by one of our professional drivers. We work with you to drive individual clients or families to their desired locations in the comfort of their vehicles, rental vehicles or motor homes.\n\nRental Truck Transportation Service\n\nYour Driving Team offers driveway-to-driveway transportation of your loaded rental trucks by one of our professional drivers, equipped with knowledge and experience in transporting large trucks. No matter the load, Your Driving Team will work with you to ensure your belongings are transported safely and conveniently. \n\nCollege Bound\n\nYour Driving Team will safely transport your child and their belongings to and from their attending colleges.\n\nVehicle Transportation\n\nSkip the drive and continue on your day to day activities. Your Driving Team will provide one of our skilled, professional drivers to relocate your car, van, pickup truck or RV to your desired destination. We ensure the highest quality of care while providing a cost-effective solution to any of your vehicle transportation needs.\n\nPersonal Pet Transportation\n\nYour Driving Team provides a personal door-to-door pet transportation services. We handle all aspect of the travel and ensure comfort and minimize stress for you and the animal the entire journey. We work with each pets specific needs and personally pair it with one of our trained professionals to drive or fly with your animal from start to finish.\n\n\nThanks,\n\nYourDrivingTeam.com    ",
	"ImageUrls": [],
	"WebSite": "YourDrivingTeam.com"
},
{
	"_id": {
		"$oid": "5db66de525dcb21797033c92"
	},
	"SourceUrl": "https://austin.craigslist.org/pas/d/austin-yourdrivingteamcom-transporting/6961566629.html",
	"PostDate": "2019-08-21T12:41:22-0500",
	"PostDateValue": "2019-08-21T12:41:22-05:00",
	"Category": "Event",
	"SubCategory": "Event Services ",
	"CategoryResolved": true,
	"CategoryResolveScore": 0.17777777777777776,
	"AddressResolved": false,
	"AddressResolveScore": 0.0,
	"Address": null,
	"Address2": null,
	"City": "austin",
	"State": "TX",
	"Zip": null,
	"Longitude": "-97.771300",
	"LongitudeValue": -97.7713,
	"Lattitude": "30.326400",
	"LattitudeValue": 30.3264,
	"PosterName": null,
	"Phone": "920-471-7017",
	"Email": null,
	"Title": "YourDrivingTeam.com Transporting of Pets through out USA.",
	"Description": "\n        \n\nYour Driving Team \n\n1:1 Pet Transport\nWhat makes us different?\n- Only your pet is transported at a time. We offer personalized service with no other pets.\n- We never use the same vehicle twice to transport pets. \n- Pet friendly drivers.\n- Clean and hygienic vehicles.\n- Care and concern to ensure your pet is happy, healthy and well cared for during the trip.\n-References upon request.\n\nPlease contact us at:\nYourDrivingTeam.com\n920-471-7017    ",
	"ImageUrls": [],
	"WebSite": "YourDrivingTeam.com"
},
{
	"_id": {
		"$oid": "5db66de525dcb21797033c93"
	},
	"SourceUrl": "https://austin.craigslist.org/aos/d/honest-mobile-mechanic/6961563580.html",
	"PostDate": "2019-08-21T12:38:02-0500",
	"PostDateValue": "2019-08-21T12:38:02-05:00",
	"Category": "Lessons",
	"SubCategory": "Music",
	"CategoryResolved": true,
	"CategoryResolveScore": 0.20666666666666664,
	"AddressResolved": false,
	"AddressResolveScore": 0.0,
	"Address": null,
	"Address2": null,
	"City": "austin",
	"State": "TX",
	"Zip": null,
	"Longitude": "-97.747200",
	"LongitudeValue": -97.7472,
	"Lattitude": "30.187600",
	"LattitudeValue": 30.1876,
	"PosterName": null,
	"Phone": "512-956-1307",
	"Email": null,
	"Title": "HONEST MOBILE MECHANIC",
	"Description": "\n        \n*ASE CERTIFIED Master Automotive Technician and Advanced Engine Specialist\n*FREE DIAGNOSTIC with purchase of recommended service\n*COMPUTER AND ELECTRICAL DIAGNOSTICS\n*Over 15 years experience in the Auto Repair Service Industry\n*HONEST\n*Hard-working\n*Serving Austin and surrounding area\n*Mobile services available\n*CALL or TEXT 512-956-1307    ",
	"ImageUrls": [],
	"WebSite": null
},
{
	"_id": {
		"$oid": "5db66de525dcb21797033c94"
	},
	"SourceUrl": "https://austin.craigslist.org/hss/d/house-cleaner-best-cleaning-book-now/6961558719.html",
	"PostDate": "2019-08-21T12:33:08-0500",
	"PostDateValue": "2019-08-21T12:33:08-05:00",
	"Category": "Household & Labor",
	"SubCategory": "Lawn service",
	"CategoryResolved": true,
	"CategoryResolveScore": 0.22222222222222224,
	"AddressResolved": false,
	"AddressResolveScore": 0.0,
	"Address": null,
	"Address2": null,
	"City": "austin",
	"State": "TX",
	"Zip": null,
	"Longitude": "0.000000",
	"LongitudeValue": 0.0,
	"Lattitude": "0.000000",
	"LattitudeValue": 0.0,
	"PosterName": null,
	"Phone": "(512) 862-7577",
	"Email": null,
	"Title": "House cleaner Best  cleaning Book now!   Background Checked Pros",
	"Description": "\n        \naffordable house cleaning options\nLet us connect you with the best rated maid service and cleaning services \nAffordable, professional maid service\n\nCALL (512) 862-7577\n\nAnas - House Cleaning\n\nHighest_Rated &amp; Most Reviewed -Maid Service Experienced Employees-. Get Custom Quotes. Highlights: Experienced, Screened &amp; Trained Employees,- Provide Necessary Cleaning Supplies- And Equipment.\nd    ",
	"ImageUrls": [],
	"WebSite": null
},
{
	"_id": {
		"$oid": "5db66de525dcb21797033c95"
	},
	"SourceUrl": "https://austin.craigslist.org/lbs/d/austin-schedule-your-move-todayno-job/6961557641.html",
	"PostDate": "2019-08-21T12:32:04-0500",
	"PostDateValue": "2019-08-21T12:32:04-05:00",
	"Category": "Lessons",
	"SubCategory": "Driving",
	"CategoryResolved": true,
	"CategoryResolveScore": 0.21428571428571433,
	"AddressResolved": false,
	"AddressResolveScore": 0.0,
	"Address": null,
	"Address2": null,
	"City": "austin",
	"State": "TX",
	"Zip": null,
	"Longitude": "-97.724200",
	"LongitudeValue": -97.7242,
	"Lattitude": "30.309300",
	"LattitudeValue": 30.3093,
	"PosterName": null,
	"Phone": "512-967-7824",
	"Email": null,
	"Title": "📋📌SCHEDULE YOUR MOVE TODAY_NO JOB TO SMALL/RATES START @ 35HR",
	"Description": "\n        \n✴we welcome same day moves\n\n✴hourly or flat rates\n\n✴load or unloading rentals,pods and ABF trailers\n\n✴no extra fees on 2-3rd floor apartments\n\n✴pick-up and delivery\n\n✴available 24/7 mover\n\n✴insured moving\n\n✴☎feel free to call about our services 512-967-7824\n\n    ",
	"ImageUrls": [],
	"WebSite": null
},
{
	"_id": {
		"$oid": "5db66de525dcb21797033c96"
	},
	"SourceUrl": "https://austin.craigslist.org/lbs/d/austin-moving-ez-movers49-always-moving/6961556879.html",
	"PostDate": "2019-08-21T12:31:17-0500",
	"PostDateValue": "2019-08-21T12:31:17-05:00",
	"Category": "Lessons",
	"SubCategory": "Driving",
	"CategoryResolved": true,
	"CategoryResolveScore": 0.21428571428571433,
	"AddressResolved": false,
	"AddressResolveScore": 0.0,
	"Address": null,
	"Address2": null,
	"City": "austin",
	"State": "TX",
	"Zip": null,
	"Longitude": "-97.765800",
	"LongitudeValue": -97.7658,
	"Lattitude": "30.242800",
	"LattitudeValue": 30.2428,
	"PosterName": null,
	"Phone": "(512) 781-4062",
	"Email": null,
	"Title": "Moving EZ MOVERS💲4️⃣9️⃣ Always Moving AUSTIN",
	"Description": "\n        \nEZ MOVERS 💲4️⃣9️⃣ HOURLY \n                                       \n                      Call FOR ☎️\n               SAME  DAY SERVICE \n                  (512) 781-4062\n                  (737) 232-9272       \n (512) 817-6602\n✅MINIMUM 2 MOVERS . \n✅MINIMUM 2 HOUR.\n✅➕20Ft Truck \n🔴Hard-Working, \n🔴Honest 🏅\n🔴Affordable Movers \n🔴Flat Rate Quote\n🔴Loading / Unloading Trucks \n🔴Packing / unpacking\n🔴Storage Moves\n🔴 Piano moving \n🔴pool table moving \n🔴Fridge moving\n✅experienced staff who will:\nRespond quickly to all inquiries\nSet up a moving date and time\nShow up on time the day of the move\nFrom corporate to residential, EZ MOVERS  is well equipped to handle all of your moving needs including:\nLocal Moving\nIntra-State Moving (aka anywhere in the state of TEXAS)\nIn-Building Moving, including apartment buildings\nBusiness Moving, including Office and Commercial Moving\nPiano Moving\nI Art and Antique Moving\nProfessional Packing Services\nLoading and Unloading    \nMoving Rates Below: \nPricing may vary slightly. \nfollows: \nMover Supplied Moving Truck and Moving Labor \n🔴2 MOVERS &amp; TRUCK $50\n🔴3 MOVERS &amp; TRUCK $80\n🔴4 MOVERS &amp; TRUCK $125\n✅MINIMUM 2 MOVERS . \n✅MINIMUM 2 HOUR. \n➕TRIP CHARGE $50.00    ",
	"ImageUrls": [
		"https://images.craigslist.org/00W0W_5BrPNG89X9K_50x50c.jpg",
		"https://images.craigslist.org/00m0m_hgxc0ECeVHv_50x50c.jpg",
		"https://images.craigslist.org/00W0W_8WvMtZsZOCf_50x50c.jpg",
		"https://images.craigslist.org/00q0q_3xULsyakPoA_50x50c.jpg",
		"https://images.craigslist.org/01111_6J5Nucvi5SB_50x50c.jpg",
		"https://images.craigslist.org/00m0m_7olynaZDAZG_50x50c.jpg",
		"https://images.craigslist.org/00404_99kqlTvTDlq_50x50c.jpg",
		"https://images.craigslist.org/01616_3JmLULk8zto_50x50c.jpg",
		"https://images.craigslist.org/00L0L_30ec3FTivQB_50x50c.jpg",
		"https://images.craigslist.org/00u0u_3n54VgqA5HP_50x50c.jpg",
		"https://images.craigslist.org/00W0W_l6Mu9vs4rl_50x50c.jpg",
		"https://images.craigslist.org/00I0I_eXTnaZfHGZW_50x50c.jpg",
		"https://images.craigslist.org/00J0J_4A1ipVTEHUR_50x50c.jpg",
		"https://images.craigslist.org/00101_hHCExM9kY7N_50x50c.jpg",
		"https://images.craigslist.org/00F0F_2NlWuuWOv6E_50x50c.jpg",
		"https://images.craigslist.org/01010_6oir6urhRgE_50x50c.jpg",
		"https://images.craigslist.org/00Y0Y_kZCt99mjLVh_50x50c.jpg",
		"https://images.craigslist.org/00T0T_cpYuUTCFhbs_50x50c.jpg",
		"https://images.craigslist.org/00l0l_jqokyAdAbO1_50x50c.jpg"
	],
	"WebSite": "50.00"
},
{
	"_id": {
		"$oid": "5db66de525dcb21797033c97"
	},
	"SourceUrl": "https://austin.craigslist.org/fgs/d/4tp-backhoe-service/6961554106.html",
	"PostDate": "2019-08-21T12:28:26-0500",
	"PostDateValue": "2019-08-21T12:28:26-05:00",
	"Category": "Household & Labor",
	"SubCategory": "Lawn service",
	"CategoryResolved": true,
	"CategoryResolveScore": 0.18888888888888888,
	"AddressResolved": false,
	"AddressResolveScore": 0.0,
	"Address": null,
	"Address2": null,
	"City": "austin",
	"State": "TX",
	"Zip": null,
	"Longitude": "-97.292100",
	"LongitudeValue": -97.2921,
	"Lattitude": "30.138800",
	"LattitudeValue": 30.1388,
	"PosterName": null,
	"Phone": null,
	"Email": null,
	"Title": "4TP Backhoe service",
	"Description": "\n        \n4TP is a top-notch excavation company. we offer affordable compact backhoe and mini excavater services.\nwe use small top of the line backhoes and mini excavaters that can reach 12ft depth and get into places full sized backhoes can not.\n\nmy goal is to reach out to the homeowners and small business by offering an expensive service for a low rate. \n$80hr includes operator.\n4hr minimum and no delivery charge for most areas\n\nDigging, trenching, leveling, walkways, driveways, tree planting, ponds, moving dirt and sand, applying and spreading roadbase, excavation, demolition, flattening, hugelkutur, permaculture, swells, farm and garden, ponds, move dirt, cutting hills,  road grading, land clearing, stump removal, livestock and horse burial, plumbing, electric, culvert installation, etc.    ",
	"ImageUrls": [
		"https://images.craigslist.org/00E0E_ebWKSkGnIC6_50x50c.jpg",
		"https://images.craigslist.org/01717_a5ac4ec4i2f_50x50c.jpg"
	],
	"WebSite": null
},
{
	"_id": {
		"$oid": "5db66de525dcb21797033c98"
	},
	"SourceUrl": "https://austin.craigslist.org/rts/d/austin-interior-house-painter-marias/6961551682.html",
	"PostDate": "2019-08-21T12:25:51-0500",
	"PostDateValue": "2019-08-21T12:25:51-05:00",
	"Category": "Household & Labor",
	"SubCategory": "Lawn service",
	"CategoryResolved": true,
	"CategoryResolveScore": 0.2,
	"AddressResolved": false,
	"AddressResolveScore": 0.0,
	"Address": null,
	"Address2": null,
	"City": "austin",
	"State": "TX",
	"Zip": null,
	"Longitude": "-97.761841",
	"LongitudeValue": -97.761841,
	"Lattitude": "30.243646",
	"LattitudeValue": 30.243646,
	"PosterName": null,
	"Phone": null,
	"Email": null,
	"Title": "INTERIOR HOUSE PAINTER! MARIA’S PAINTING !",
	"Description": "\n        \nInterior painting/repaints!\nTouch-ups!\nExpert drywall repair/texture match!\nBrush, roll, spray!\nFast, clean, affordable!\nReferences upon request!\nSatisfaction guaranteed!\nA+ rating with BBB!\nFully insured 1+2\nFull coverage commercial insurance on van\nAsk about our affordable day rate!\nFree estimates!    ",
	"ImageUrls": [
		"https://images.craigslist.org/00606_15Eyj9BH7Cu_50x50c.jpg",
		"https://images.craigslist.org/00Y0Y_23rrSvzKGeN_50x50c.jpg",
		"https://images.craigslist.org/00a0a_jJrKR45MsPN_50x50c.jpg",
		"https://images.craigslist.org/00000_487iiYiw9pb_50x50c.jpg",
		"https://images.craigslist.org/00s0s_ilbJKezV4LF_50x50c.jpg",
		"https://images.craigslist.org/00808_ct2StLM3QHx_50x50c.jpg",
		"https://images.craigslist.org/00u0u_8IjQaZbSqTN_50x50c.jpg",
		"https://images.craigslist.org/00e0e_jYmIBTKhcZY_50x50c.jpg",
		"https://images.craigslist.org/01717_bBof20aDJbh_50x50c.jpg",
		"https://images.craigslist.org/00G0G_k84nMAykfqD_50x50c.jpg",
		"https://images.craigslist.org/00j0j_PMLuzzgqU2_50x50c.jpg",
		"https://images.craigslist.org/00202_hpMEmzso3ej_50x50c.jpg",
		"https://images.craigslist.org/00404_hKY1wtkzaIb_50x50c.jpg",
		"https://images.craigslist.org/00x0x_2yXcWBH18s9_50x50c.jpg",
		"https://images.craigslist.org/00W0W_7bpIGkQrRof_50x50c.jpg",
		"https://images.craigslist.org/00A0A_459zjOumAg_50x50c.jpg",
		"https://images.craigslist.org/00I0I_GpvzOB4A1T_50x50c.jpg",
		"https://images.craigslist.org/00N0N_2au7ROVm2g7_50x50c.jpg"
	],
	"WebSite": null
},
{
	"_id": {
		"$oid": "5db66de525dcb21797033c99"
	},
	"SourceUrl": "https://austin.craigslist.org/hss/d/hutto-looking-for-cleaning-services/6961550488.html",
	"PostDate": "2019-08-21T12:24:33-0500",
	"PostDateValue": "2019-08-21T12:24:33-05:00",
	"Category": "Household & Labor",
	"SubCategory": "Lawn service",
	"CategoryResolved": true,
	"CategoryResolveScore": 0.22222222222222224,
	"AddressResolved": false,
	"AddressResolveScore": 0.0,
	"Address": null,
	"Address2": null,
	"City": "austin",
	"State": "TX",
	"Zip": null,
	"Longitude": "-97.567200",
	"LongitudeValue": -97.5672,
	"Lattitude": "30.525700",
	"LattitudeValue": 30.5257,
	"PosterName": null,
	"Phone": null,
	"Email": null,
	"Title": "LOOKING FOR CLEANING SERVICES?? LOOK NO FURTHER!!!!",
	"Description": "\n        \nMeet the pickiest housekeeper around! I'm an EXTREMELY hard worker and expect nothing less than perfection offering reasonable prices! Your 100% satisfaction is my priority! I am available to clean your home and/or business. I service Austin, Cedar Park and Round Rock, Hutto, and Taylor areas. Please EMAIL or TEXT me with your needs for a price today!    ",
	"ImageUrls": [],
	"WebSite": null
},
{
	"_id": {
		"$oid": "5db66de525dcb21797033c9a"
	},
	"SourceUrl": "https://austin.craigslist.org/biz/d/austin-interior-house-painter-marias/6961550490.html",
	"PostDate": "2019-08-21T12:24:33-0500",
	"PostDateValue": "2019-08-21T12:24:33-05:00",
	"Category": null,
	"SubCategory": "small biz ads",
	"CategoryResolved": false,
	"CategoryResolveScore": 0.3,
	"AddressResolved": false,
	"AddressResolveScore": 0.0,
	"Address": null,
	"Address2": null,
	"City": "austin",
	"State": "TX",
	"Zip": null,
	"Longitude": "-97.761841",
	"LongitudeValue": -97.761841,
	"Lattitude": "30.243646",
	"LattitudeValue": 30.243646,
	"PosterName": null,
	"Phone": null,
	"Email": null,
	"Title": "INTERIOR HOUSE PAINTER! MARIA’S PAINTING !",
	"Description": "\n        \nInterior painting/repaints!\nTouch-ups!\nExpert drywall repair/texture match!\nBrush, roll, spray!\nFast, clean, affordable!\nReferences upon request!\nSatisfaction guaranteed!\nA+ rating with BBB!\nFully insured 1+2\nFull coverage commercial insurance on van\nAsk about our affordable day rate!\nFree estimates!    ",
	"ImageUrls": [
		"https://images.craigslist.org/00606_15Eyj9BH7Cu_50x50c.jpg",
		"https://images.craigslist.org/00Y0Y_23rrSvzKGeN_50x50c.jpg",
		"https://images.craigslist.org/00a0a_jJrKR45MsPN_50x50c.jpg",
		"https://images.craigslist.org/00000_487iiYiw9pb_50x50c.jpg",
		"https://images.craigslist.org/00s0s_ilbJKezV4LF_50x50c.jpg",
		"https://images.craigslist.org/00808_ct2StLM3QHx_50x50c.jpg",
		"https://images.craigslist.org/00u0u_8IjQaZbSqTN_50x50c.jpg",
		"https://images.craigslist.org/00e0e_jYmIBTKhcZY_50x50c.jpg",
		"https://images.craigslist.org/01717_bBof20aDJbh_50x50c.jpg",
		"https://images.craigslist.org/00G0G_k84nMAykfqD_50x50c.jpg",
		"https://images.craigslist.org/00j0j_PMLuzzgqU2_50x50c.jpg",
		"https://images.craigslist.org/00202_hpMEmzso3ej_50x50c.jpg",
		"https://images.craigslist.org/00404_hKY1wtkzaIb_50x50c.jpg",
		"https://images.craigslist.org/00x0x_2yXcWBH18s9_50x50c.jpg",
		"https://images.craigslist.org/00W0W_7bpIGkQrRof_50x50c.jpg",
		"https://images.craigslist.org/00A0A_459zjOumAg_50x50c.jpg",
		"https://images.craigslist.org/00I0I_GpvzOB4A1T_50x50c.jpg",
		"https://images.craigslist.org/00N0N_2au7ROVm2g7_50x50c.jpg"
	],
	"WebSite": null
},
{
	"_id": {
		"$oid": "5db66de525dcb21797033c9b"
	},
	"SourceUrl": "https://austin.craigslist.org/fns/d/austin-business-and-alternative-loans/6961550452.html",
	"PostDate": "2019-08-21T12:24:31-0500",
	"PostDateValue": "2019-08-21T12:24:31-05:00",
	"Category": "Household & Labor",
	"SubCategory": "Lawn service",
	"CategoryResolved": true,
	"CategoryResolveScore": 0.18888888888888888,
	"AddressResolved": false,
	"AddressResolveScore": 0.0,
	"Address": null,
	"Address2": null,
	"City": "austin",
	"State": "TX",
	"Zip": null,
	"Longitude": "-97.690887",
	"LongitudeValue": -97.690887,
	"Lattitude": "30.258746",
	"LattitudeValue": 30.258746,
	"PosterName": null,
	"Phone": "000 regardl",
	"Email": "luisyepez@fundedcapital.com",
	"Title": "Business and Alternative Loans/Financing",
	"Description": "\n        \nGuaranteed Approval Business Funding with 90% approval rate. we offer up to $25,000,000 regardless of credit history. We offer both unsecured and secured programs.\n\nWe work with several private hedge funds and over 150 conventional lenders, private banks and financial institutions. Our options to get you the financing you need are endless.\n\nWe specialize in:\n\nBusiness Term Loans. 1-10 year terms with rates starting at 8.99%.\nBusiness Line of Credit. 1 year term. Rates starting at 1% (monthly).\nAR and Invoice Factoring. 6 - 36 month term. Rates starting at 5%.\nEquipment Leasing and Financing. 12-48 month terms. Rates starting at 8.99%.\nWorking Capital Loans. 3 - 24 month terms. Rates starting at 10.99%. \n\nWe recently introduced our new system; CIRGO. This is our brand new automated AI Lending Platform. CIRGO is programmed to automatically connect with all qualifying lenders for YOUR specific business and loan type. It calculates risk, cash flow, revenue patterns and ROI. This allows us to service our clients in a more timely and efficient manner.\n\nMinimum to qualify:\n- Must be in business 4 months.\n- Must make a minimum $10k in monthly revenue (in actual bank deposits per month for last 2 consecutive months each month).\n- Must have an U.S business checking account were deposits are made.\n- Must be operating in the US, Puerto Rico and Canada.\n- Minimum credit score of 450\n\nFeel free to email me directly at luisyepez@fundedcapital.com or visit our website www.fundedcapital.com, so we can initiate the process. We can typically have an offer formulated within 12-48 hours of receiving application, and we offer same day funding options.\n\nSIMPLE WAY TO GROW YOUR BUSINESS    ",
	"ImageUrls": [],
	"WebSite": "8.99"
},
{
	"_id": {
		"$oid": "5db66de525dcb21797033c9c"
	},
	"SourceUrl": "https://austin.craigslist.org/sks/d/bastrop-4tp-excavation-service/6961550009.html",
	"PostDate": "2019-08-21T12:24:03-0500",
	"PostDateValue": "2019-08-21T12:24:03-05:00",
	"Category": "Household & Labor",
	"SubCategory": "Lawn service",
	"CategoryResolved": true,
	"CategoryResolveScore": 0.2,
	"AddressResolved": false,
	"AddressResolveScore": 0.0,
	"Address": null,
	"Address2": null,
	"City": "austin",
	"State": "TX",
	"Zip": null,
	"Longitude": "-97.298784",
	"LongitudeValue": -97.298784,
	"Lattitude": "30.158376",
	"LattitudeValue": 30.158376,
	"PosterName": null,
	"Phone": null,
	"Email": null,
	"Title": "4TP Excavation Service",
	"Description": "\n        \n4TP Excavation is an excavation company in Bastrop and surrounding areas.\n$80 per hour \nMid-sized backhoes (9,800lbs) to get into smaller areas.\nDig to 12' with speed and precision.\nMini excavator (4,800lbs) to get into tight spots ( tracks suck in to fit through a 38\" space with a dig depth of 10'. \n***call 214 7O8 653O for Jonathon Smith or 512 545 443O for Office***\n\nOur scope of work includes but is not limited to: Digging, trenching, leveling, walkways, driveways, tree planting, ponds, pools, moving dirt and sand, applying and spreading roadbase, excavation, demolition, flattening, hugelkutur, permaculture, swells, farm and garden, cutting hills,  road grading, land clearing, stump removal, livestock and horse burial, plumbing, electric, culvert installation, etc.\n\n4hr minimum and no delivery charge for most areas in Bastrop County\n    ",
	"ImageUrls": [
		"https://images.craigslist.org/01717_a5ac4ec4i2f_50x50c.jpg",
		"https://images.craigslist.org/00E0E_ebWKSkGnIC6_50x50c.jpg",
		"https://images.craigslist.org/00h0h_gZYmDDnT4ph_50x50c.jpg",
		"https://images.craigslist.org/00R0R_7g7e954H4uQ_50x50c.jpg",
		"https://images.craigslist.org/00G0G_4K3RLFGfvdK_50x50c.jpg",
		"https://images.craigslist.org/00E0E_fQpWEPQX58W_50x50c.jpg",
		"https://images.craigslist.org/00707_eoO0J0ndImd_50x50c.jpg",
		"https://images.craigslist.org/00P0P_a0YYy6tLhN6_50x50c.jpg"
	],
	"WebSite": null
},
















{
	"_id": {
		"$oid": "5db66de525dcb21797033ca6"
	},
	"SourceUrl": "https://austin.craigslist.org/sks/d/austin-lowest-prices-honest-painters/6961521440.html",
	"PostDate": "2019-08-21T11:54:21-0500",
	"PostDateValue": "2019-08-21T11:54:21-05:00",
	"Category": "Household & Labor",
	"SubCategory": "Lawn service",
	"CategoryResolved": true,
	"CategoryResolveScore": 0.2,
	"AddressResolved": false,
	"AddressResolveScore": 0.0,
	"Address": null,
	"Address2": null,
	"City": "austin",
	"State": "TX",
	"Zip": null,
	"Longitude": "-97.742600",
	"LongitudeValue": -97.7426,
	"Lattitude": "30.271300",
	"LattitudeValue": 30.2713,
	"PosterName": null,
	"Phone": null,
	"Email": null,
	"Title": "Lowest Prices / Honest Painters / Painting / Painter Service!!",
	"Description": "\n        \nLooking to paint your house, apartment or business? Give us a call for your next project. Our company is committed to offer quality and reliable work to our all customers. You can count on our professional and honest team and we will make sure you’re satisfied with our services.\n\nWe are serving the Austin and surrounding areas from 15 years and available all 7 days a week for work. References are available upon request.\n\nGive us a call today and get a free estimate!!\n\n~exterior &amp; interior painting \n~houses/studios/custom homes/apt. Etc.\n~carpentry/stucco\n~drywall repair \n~sheetrock repair\n~pressure washing\n~wallpaper removing\n~painter\n~painters\n~financing available\n~popcorn removal\n~free estimates\n\nWe are offering lowest prices! We can beat any estimate!\n\nResidential or commercial, interior or exterior, no job is too big or too small for us, we've got you covered with our years of expertise and skills! Give us a call today for a free in-home estimate!    ",
	"ImageUrls": [],
	"WebSite": null
},
{
	"_id": {
		"$oid": "5db66de525dcb21797033ca7"
	},
	"SourceUrl": "https://austin.craigslist.org/lgs/d/divorce-custody-child-support-paternity/6961519408.html",
	"PostDate": "2019-08-21T11:52:07-0500",
	"PostDateValue": "2019-08-21T11:52:07-05:00",
	"Category": "Household & Labor",
	"SubCategory": "Lawn service",
	"CategoryResolved": true,
	"CategoryResolveScore": 0.2,
	"AddressResolved": false,
	"AddressResolveScore": 0.0,
	"Address": null,
	"Address2": null,
	"City": "austin",
	"State": "TX",
	"Zip": null,
	"Longitude": "-97.645391",
	"LongitudeValue": -97.645391,
	"Lattitude": "30.496310",
	"LattitudeValue": 30.49631,
	"PosterName": null,
	"Phone": "(512) 924-2939",
	"Email": null,
	"Title": "Divorce • Custody • Child Support • Paternity • Adoptions",
	"Description": "\n        \nTRUSTWORTHY | EFFICIENT | RESULTS-DRIVEN\n\nCall us today! (512) 924-2939\n\nDivorce, Child Custody, Child Support, Paternity, Termination and Adoptions\nChild Custody Modifications, Child Custody and Child Support Enforcement\nName Change\n\nNo children? No property?\nUncontested divorces for $399 (plus filing fees). Limited time pricing. \nAffordable retainers and low monthly payments on all other cases.\n\nQuestions? Contact us at (512) 924-2939.\n\nHinson Singla, PLLC | 2251 Double Creek Drive, Suite 601, Round Rock, Texas 78664\n\nwww.hinsonsingla.com\n\nTRUSTWORTHY | EFFICIENT | RESULTS-DRIVEN    ",
	"ImageUrls": [
		"https://images.craigslist.org/00I0I_4a32K8oiRAE_50x50c.jpg",
		"https://images.craigslist.org/00n0n_1qcFquu48ko_50x50c.jpg"
	],
	"WebSite": "www.hinsonsingla.com"
},
{
	"_id": {
		"$oid": "5db66de525dcb21797033ca8"
	},
	"SourceUrl": "https://austin.craigslist.org/sks/d/round-rock-sullivans-plumbing-services/6961518240.html",
	"PostDate": "2019-08-21T11:50:52-0500",
	"PostDateValue": "2019-08-21T11:50:52-05:00",
	"Category": "Household & Labor",
	"SubCategory": "Lawn service",
	"CategoryResolved": true,
	"CategoryResolveScore": 0.2,
	"AddressResolved": false,
	"AddressResolveScore": 0.0,
	"Address": null,
	"Address2": null,
	"City": "austin",
	"State": "TX",
	"Zip": null,
	"Longitude": "-97.668000",
	"LongitudeValue": -97.668,
	"Lattitude": "30.514500",
	"LattitudeValue": 30.5145,
	"PosterName": null,
	"Phone": "(512) 599-4565",
	"Email": null,
	"Title": "Sullivan&#39;s Plumbing Services -  Free Estimates , Low Prices, Save $$$$",
	"Description": "\n        \nSullivans Plumbing Services, A Plumbing company with 15 years of experience that is new to the Austin Area.  A local and affordable company that can save you $$$ CALL NOW (512) 599-4565  If you're in need of a Plumber, why not hire an actually local company too give you a FREE ESTIMATE and then perform the work if you like the price, if you don't like the price no CHARGE!  Call Now (512) 599-4565 and speak with ME to get fast, friendly, and affordable plumbing service! \n\n10% SENIOR AND  VET DISCOUNTS!! \n\nServices Offered:  ANYTHING PLUMBING RELATED!!!  Toilet Repair / Replacement, Sink and Faucet Repair / Replacement,  Water Heater Repair, Water Heater Replacement, Slab Leak Locate, Slab Leak Repair, Shower / Bathtub Repair, Disposal Repair, Leak Locate and Repair, Small And Large Drain Cleaning, Water Softener and Filter Install / Repair, Re-Pipe Home, Fix Broken Pipe, Shutoff Valves and Pressure Regulation Valves, Broken Pipe, Broken Drain, Broken Sewer Line.  IF IT USES WATER I CAN FIX IT.    ",
	"ImageUrls": [],
	"WebSite": null
},
{
	"_id": {
		"$oid": "5db66de525dcb21797033ca9"
	},
	"SourceUrl": "https://austin.craigslist.org/sks/d/austin-roofing-roof-replacement-repairs/6961517154.html",
	"PostDate": "2019-08-21T11:49:45-0500",
	"PostDateValue": "2019-08-21T11:49:45-05:00",
	"Category": "Household & Labor",
	"SubCategory": "Lawn service",
	"CategoryResolved": true,
	"CategoryResolveScore": 0.2,
	"AddressResolved": false,
	"AddressResolveScore": 0.0,
	"Address": null,
	"Address2": null,
	"City": "austin",
	"State": "TX",
	"Zip": null,
	"Longitude": "-97.742600",
	"LongitudeValue": -97.7426,
	"Lattitude": "30.271300",
	"LattitudeValue": 30.2713,
	"PosterName": null,
	"Phone": null,
	"Email": null,
	"Title": "Roofing / Roof Replacement / Repairs / Re-roofing / Roofer!!",
	"Description": "\n        \nOur company is specialized in roofing and roof repairs! We guarantee quality materials for all types of roofing. We take pride in every single job and no project is too small for us, we focus on one job at a time and which is how we are able to maintain our customer satisfaction at 100%.\n\nOur roofing company is available to fix all of your roofing needs from leeks to full replacement, We can do it all.\n\nServices:\n- Metal roofing\n- Shingle roofing\n- Wood roofing\n- Flat roofing\n- Roof repairs\n- Roof replacement\n- Roof inspection \n\nTake the first step to increasing the value of your home with a stylish and durable roof! \n\nWe have over 15 years of experience in the roofing business. We are licensed by all major manufacturers for installation and fabrication. Contact us now for a free consultation and estimate!    ",
	"ImageUrls": [],
	"WebSite": null
},
{
	"_id": {
		"$oid": "5db66de525dcb21797033caa"
	},
	"SourceUrl": "https://austin.craigslist.org/lbs/d/labor-kings-loads-unloads-same-day/6961515327.html",
	"PostDate": "2019-08-21T11:47:46-0500",
	"PostDateValue": "2019-08-21T11:47:46-05:00",
	"Category": "Lessons",
	"SubCategory": "Driving",
	"CategoryResolved": true,
	"CategoryResolveScore": 0.21428571428571433,
	"AddressResolved": false,
	"AddressResolveScore": 0.0,
	"Address": null,
	"Address2": null,
	"City": "austin",
	"State": "TX",
	"Zip": null,
	"Longitude": "0.000000",
	"LongitudeValue": 0.0,
	"Lattitude": "0.000000",
	"LattitudeValue": 0.0,
	"PosterName": null,
	"Phone": "(512)460-0014",
	"Email": null,
	"Title": "LABOR KINGS-LOADS/UNLOADS-SAME DAY SERVICE!",
	"Description": "\n        \nLabor Services\nWhile we specialize in taking items to other locations, you can also hire us to lift heavy items in your home or load objects on your PODS container, truck, or trailer. As one of strongest lifting crews in Texas, we have the ability to lift various items for you. (512)460-0014 or Book Online @ www.moving-texas.com    ",
	"ImageUrls": [
		"https://images.craigslist.org/01414_kYvnt88cNTE_50x50c.jpg",
		"https://images.craigslist.org/00C0C_8X6rafHhp4t_50x50c.jpg"
	],
	"WebSite": "www.moving-texas.com"
},
{
	"_id": {
		"$oid": "5db66de525dcb21797033cab"
	},
	"SourceUrl": "https://austin.craigslist.org/fgs/d/austin-lms-landscaping/6961511249.html",
	"PostDate": "2019-08-21T11:43:37-0500",
	"PostDateValue": "2019-08-21T11:43:37-05:00",
	"Category": "Household & Labor",
	"SubCategory": "Lawn service",
	"CategoryResolved": true,
	"CategoryResolveScore": 0.18888888888888888,
	"AddressResolved": false,
	"AddressResolveScore": 0.0,
	"Address": null,
	"Address2": null,
	"City": "austin",
	"State": "TX",
	"Zip": null,
	"Longitude": "-97.731763",
	"LongitudeValue": -97.731763,
	"Lattitude": "30.434316",
	"LattitudeValue": 30.434316,
	"PosterName": null,
	"Phone": "512 775 7723",
	"Email": null,
	"Title": "LMS Landscaping",
	"Description": "\n        \n**LANDSCAPING SERVICES**\n-Landscape design \n-Landsape installation\n-Fire pits\n-Walkways and patios Installation\n-Stone work\n-Retaining walls\n\n\nFeel free to contact us for your next project!\nText or call:\n512 775 7723\n\n *FREE ESTIMATES*    ",
	"ImageUrls": [
		"https://images.craigslist.org/00i0i_22IR9TFqqbC_50x50c.jpg",
		"https://images.craigslist.org/00707_f93b7LqPyw2_50x50c.jpg",
		"https://images.craigslist.org/00I0I_ayLD8k9d7vp_50x50c.jpg",
		"https://images.craigslist.org/00n0n_lGsgYMyAgaK_50x50c.jpg",
		"https://images.craigslist.org/00V0V_hrWSlKfFLir_50x50c.jpg",
		"https://images.craigslist.org/00n0n_1LDi4DiroIb_50x50c.jpg",
		"https://images.craigslist.org/00H0H_cC9i1knuBNA_50x50c.jpg",
		"https://images.craigslist.org/00v0v_auRX2Rs2I5v_50x50c.jpg",
		"https://images.craigslist.org/01717_5nNQoF97vBf_50x50c.jpg",
		"https://images.craigslist.org/00606_d5HlQ7wtb3U_50x50c.jpg",
		"https://images.craigslist.org/00R0R_5VIvLUVtYMS_50x50c.jpg",
		"https://images.craigslist.org/00H0H_irCds55x6Hm_50x50c.jpg",
		"https://images.craigslist.org/01010_dxiWgzf9ixa_50x50c.jpg",
		"https://images.craigslist.org/00P0P_7N17S64ApSU_50x50c.jpg",
		"https://images.craigslist.org/00G0G_alxdE8J1bIA_50x50c.jpg",
		"https://images.craigslist.org/00V0V_3oJ7bUXN8Nu_50x50c.jpg",
		"https://images.craigslist.org/00z0z_9qnQHaKmMMI_50x50c.jpg",
		"https://images.craigslist.org/00f0f_8SHg5qSX4Ha_50x50c.jpg"
	],
	"WebSite": null
},
{
	"_id": {
		"$oid": "5db66de525dcb21797033cac"
	},
	"SourceUrl": "https://austin.craigslist.org/sks/d/austin-semi-retired-handy-man-at-age-58/6961510867.html",
	"PostDate": "2019-08-21T11:43:15-0500",
	"PostDateValue": "2019-08-21T11:43:15-05:00",
	"Category": "Household & Labor",
	"SubCategory": "Lawn service",
	"CategoryResolved": true,
	"CategoryResolveScore": 0.2,
	"AddressResolved": false,
	"AddressResolveScore": 0.0,
	"Address": null,
	"Address2": null,
	"City": "austin",
	"State": "TX",
	"Zip": null,
	"Longitude": "-97.822500",
	"LongitudeValue": -97.8225,
	"Lattitude": "30.174300",
	"LattitudeValue": 30.1743,
	"PosterName": null,
	"Phone": null,
	"Email": null,
	"Title": "SEMI RETIRED HANDY MAN-AT AGE 58 I&#39;M HONEST AND MATURE",
	"Description": "\n        \nWE CAN DO JUST ABOUT ANYTHING AND ARE EAGER TO SERVE YOU, WE DO PAINTING INSIDE AND OUT, SHEETROCK, FLOORING-LAMINATE AND TILE, TUBS SHOWERS, DECKS- FENCING, WINDOWS AND DOORS, KITCHEN AND BATH REMODEL. 27 YEARS EXPERIENCE. CIELING FANS, LIGHT ELECTRICAL AND PLUMBING. WE AIME TO PLEASE.    ",
	"ImageUrls": [
		"https://images.craigslist.org/00J0J_cmlD0dV0AIi_50x50c.jpg",
		"https://images.craigslist.org/00u0u_fFpCSXU3WBo_50x50c.jpg"
	],
	"WebSite": null
},
{
	"_id": {
		"$oid": "5db66de525dcb21797033cad"
	},
	"SourceUrl": "https://austin.craigslist.org/sks/d/austin-home-renovation-services-offered/6961505161.html",
	"PostDate": "2019-08-21T11:37:33-0500",
	"PostDateValue": "2019-08-21T11:37:33-05:00",
	"Category": "Household & Labor",
	"SubCategory": "Lawn service",
	"CategoryResolved": true,
	"CategoryResolveScore": 0.2,
	"AddressResolved": false,
	"AddressResolveScore": 0.0,
	"Address": null,
	"Address2": null,
	"City": "austin",
	"State": "TX",
	"Zip": null,
	"Longitude": "-97.795600",
	"LongitudeValue": -97.7956,
	"Lattitude": "30.206300",
	"LattitudeValue": 30.2063,
	"PosterName": null,
	"Phone": "512-605-7749",
	"Email": null,
	"Title": "Home Renovation Services Offered and Much More",
	"Description": "\n        \nA LITTLE ABOUT US\nThe Construction Company You Can Depend On\n\n Lay It down Construction Co. has been a reliable Austin Construction Company since 2016. Being a great service provider means having complete and total confidence in the people providing those services, and we're proud to have the best pros in the business working with us. With a focus on personalized service, competitive rates, and customer satisfaction, we're always striving to meet and exceed our high standards and our clients' expectations.\n\nWe do it all! \n\nPlease gives us a call at 512-605-7749 - Thanks Joshua    ",
	"ImageUrls": [],
	"WebSite": null
},
{
	"_id": {
		"$oid": "5db66de525dcb21797033cae"
	},
	"SourceUrl": "https://austin.craigslist.org/sks/d/painterdiscountpaintingdiscountpaintitau/6961502581.html",
	"PostDate": "2019-08-21T11:35:00-0500",
	"PostDateValue": "2019-08-21T11:35:00-05:00",
	"Category": "Household & Labor",
	"SubCategory": "Lawn service",
	"CategoryResolved": true,
	"CategoryResolveScore": 0.2,
	"AddressResolved": false,
	"AddressResolveScore": 0.0,
	"Address": null,
	"Address2": null,
	"City": "austin",
	"State": "TX",
	"Zip": null,
	"Longitude": "-97.724200",
	"LongitudeValue": -97.7242,
	"Lattitude": "30.309300",
	"LattitudeValue": 30.3093,
	"PosterName": null,
	"Phone": null,
	"Email": null,
	"Title": "Painter***Discount**Painting***Discount********Paint***It*Austin****",
	"Description": "\n        \n*Painting** Painters*Austin Painter*Interior Painting*Exterior*Painter AMAZING Local Painting has NEVER been this affordable If you're in need of a local true best choice for painting services you should choose your local #1 choice Our EXPEDIENT squad completes your painting job &amp; gives the custom-tailored painting amazing painting packages and you'll get by far the top compromise between low cost and high quality Give us a Ring Today We offer limited time pricing     ",
	"ImageUrls": [
		"https://images.craigslist.org/00606_19KysGpQZJz_50x50c.jpg",
		"https://images.craigslist.org/00G0G_i73LWujM0I1_50x50c.jpg",
		"https://images.craigslist.org/00t0t_6AuzRpAsQhK_50x50c.jpg",
		"https://images.craigslist.org/01313_l1zCGGqb444_50x50c.jpg",
		"https://images.craigslist.org/00w0w_lI374WjTw17_50x50c.jpg",
		"https://images.craigslist.org/00F0F_3RQEkMdvi1d_50x50c.jpg",
		"https://images.craigslist.org/00m0m_4xfNwub1UjI_50x50c.jpg",
		"https://images.craigslist.org/00808_55dcdiYqws7_50x50c.jpg",
		"https://images.craigslist.org/01515_hggbH95d34r_50x50c.jpg",
		"https://images.craigslist.org/00e0e_7NiAJRxjLqF_50x50c.jpg",
		"https://images.craigslist.org/00v0v_3ySMgW0pzhm_50x50c.jpg",
		"https://images.craigslist.org/00r0r_3HJJseyiJpq_50x50c.jpg",
		"https://images.craigslist.org/00Q0Q_lvYzORZsNyS_50x50c.jpg",
		"https://images.craigslist.org/01515_aA8azesQPfJ_50x50c.jpg",
		"https://images.craigslist.org/00K0K_d8gkPdU4G1Z_50x50c.jpg",
		"https://images.craigslist.org/00N0N_au1rsuYvcer_50x50c.jpg",
		"https://images.craigslist.org/00A0A_5aCwCG9o0Hu_50x50c.jpg",
		"https://images.craigslist.org/00Q0Q_eVH8Dg2jpdP_50x50c.jpg"
	],
	"WebSite": null
}]