module.exports.data = [{"id":"1","service_post_id":"3","is_helpful":"1","review_id":"1","user_id":"5"}, {"id":"2","service_post_id":"7","is_helpful":"0","review_id":"6","user_id":"6"}, 
{"id":"3","service_post_id":"7","is_helpful":"1","review_id":"5","user_id":"6"}, {"id":"4","service_post_id":"7","is_helpful":"1","review_id":"7","user_id":"6"}, 
{"id":"5","service_post_id":"7","is_helpful":"1","review_id":"9","user_id":"6"}, {"id":"6","service_post_id":"7","is_helpful":"0","review_id":"8","user_id":"6"}, 
{"id":"7","service_post_id":"3","is_helpful":"0","review_id":"2","user_id":"5"}, {"id":"8","service_post_id":"7","is_helpful":"1","review_id":"10","user_id":"5"}, 
{"id":"9","service_post_id":"7","is_helpful":"1","review_id":"7","user_id":"5"}, {"id":"10","service_post_id":"7","is_helpful":"1","review_id":"8","user_id":"5"}, 
{"id":"11","service_post_id":"7","is_helpful":"0","review_id":"11","user_id":"5"}, {"id":"12","service_post_id":"3","is_helpful":"1","review_id":"1","user_id":"6"}, 
{"id":"13","service_post_id":"3","is_helpful":"1","review_id":"2","user_id":"6"}, {"id":"14","service_post_id":"3","is_helpful":"1","review_id":"3","user_id":"6"},
{"id":"15","service_post_id":"3","is_helpful":"1","review_id":"4","user_id":"6"}, {"id":"16","service_post_id":"3","is_helpful":"1","review_id":"4","user_id":"38"}, 
{"id":"17","service_post_id":"3","is_helpful":"1","review_id":"13","user_id":"38"}, {"id":"18","service_post_id":"3","is_helpful":"1","review_id":"13","user_id":"6"}, 
{"id":"19","service_post_id":"3","is_helpful":"1","review_id":"14","user_id":"6"}, {"id":"20","service_post_id":"3","is_helpful":"0","review_id":"14","user_id":"5"},
{"id":"21","service_post_id":"3","is_helpful":"0","review_id":"15","user_id":"6"}, {"id":"22","service_post_id":"34","is_helpful":"1","review_id":"17","user_id":"12"},
{"id":"23","service_post_id":"3","is_helpful":"1","review_id":"1","user_id":"20"}, {"id":"24","service_post_id":"3","is_helpful":"0","review_id":"3","user_id":"20"}, 
{"id":"25","service_post_id":"3","is_helpful":"1","review_id":"4","user_id":"20"}, {"id":"26","service_post_id":"34","is_helpful":"1","review_id":"17","user_id":"20"}, 
{"id":"27","service_post_id":"34","is_helpful":"1","review_id":"17","user_id":"6"}, {"id":"28","service_post_id":"37","is_helpful":"1","review_id":"20","user_id":"6"},
{"id":"29","service_post_id":"34","is_helpful":"1","review_id":"21","user_id":"6"}, {"id":"30","service_post_id":"34","is_helpful":"1","review_id":"21","user_id":"6"}, 
{"id":"31","service_post_id":"34","is_helpful":"1","review_id":"21","user_id":"12"}, {"id":"32","service_post_id":"81","is_helpful":"1","review_id":"23","user_id":"6"}, 
{"id":"33","service_post_id":"81","is_helpful":"0","review_id":"24","user_id":"6"}, {"id":"34","service_post_id":"34","is_helpful":"1","review_id":"22","user_id":"6"}, {
"id":"35","service_post_id":"34","is_helpful":"0","review_id":"22","user_id":"20"}, {"id":"36","service_post_id":"44","is_helpful":"1","review_id":"26","user_id":"6"}, 
{"id":"37","service_post_id":"34","is_helpful":"1","review_id":"29","user_id":"20"}];